# -*- coding: utf-8 -*-
"""ESG302 Computer Project - Matthew Goldfarb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KedwJRHh_h9S68V2rC8Az43fcPKnBjSh
"""

def f(T,a,b,c,d,e):
    return a + b*T + c*T**2 + d*T**3 + (e/T**2) #Make the original function Cp,m

def simpson_entropy(T1,T2,n,a,b,c,d,e): #All the variables fir this
    def g(T):
        return f(T,a,b,c,d,e)/T #Same as enthalphy just dividing by the whole function by the T variable for every iteration
    dx=(T2-T1)/n #The rate of change between each interval
    sum=(g(T2)+g(T1))*(dx/3) #Include the first and last term which are multiplied by a coefficiant of 1
    for i in range(1,n):
        if i%2==1: #All the terms where the coefficient is 4
            sum+=4*(dx/3)*g(T1+dx*(i)) #divide the rate of change by 3 and add the overall number to the sum
        if i%2==0: #All the terms where the coefficient is 2
            sum+=2*(dx/3)*g(T1+dx*(i))
    return sum

def simpson_enthalpy(T1,T2,n,a,b,c,d,e):
    def g(T):
        return f(T,a,b,c,d,e)
    dx=(T2-T1)/n
    sum=(g(T2)+g(T1))*(dx/3)
    for i in range(1,n):
        if i%2==1:
            sum+=4*(dx/3)*g(T1+dx*(i))
        if i%2==0:
            sum+=2*(dx/3)*g(T1+dx*(i))
    return sum

#Make the user input all the values
a=float(input("Enter a value for a: ")) #25.00
b=float(input("Enter a value for b: ")) #55.19
c=float(input("Enter a value for c: ")) #-33.69
d=float(input("Enter a value for d: ")) #7.95
e=float(input("Enter a value for e: ")) #-.14
T1=float(input("Enter T1: "))
T2=float(input("Enter T2: "))
n=int(input("Enter the number of intervals: "))
print(' ')
print('Enthalpy:', simpson_enthalpy(T1,T2,n,a,b,c,d,e), 'J/K*mol')
print('Entropy: ',simpson_entropy(T1,T2,n,a,b,c,d,e),'J/K*mol')